In [27]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import AdaBoostRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_squared_error
import warnings
warnings.filterwarnings('ignore')
from sklearn.neighbors import KNeighborsRegressor
from sklearn.decomposition import PCA
from sklearn.model_selection import GridSearchCV
import pickle
from sklearn.model_selection import cross_val_score

In [2]:
df=pd.read_csv('ad.csv')

In [3]:
df.head()

Unnamed: 0     TV  radio  newspaper  sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9

In [11]:
df.columns=new_cols

In [10]:
new_cols=['drop','TV', 'radio', 'newspaper', 'sales']

In [12]:
df.drop('drop',axis=1,inplace=True)

In [13]:
df.isnull().sum()

TV           0
radio        0
newspaper    0
sales        0
dtype: int64

In [14]:
df.describe()

TV       radio   newspaper       sales
count  200.000000  200.000000  200.000000  200.000000
mean   147.042500   23.264000   30.554000   14.022500
std     85.854236   14.846809   21.778621    5.217457
min      0.700000    0.000000    0.300000    1.600000
25%     74.375000    9.975000   12.750000   10.375000
50%    149.750000   22.900000   25.750000   12.900000
75%    218.825000   36.525000   45.100000   17.400000
max    296.400000   49.600000  114.000000   27.000000

In [15]:
df.corr()

TV     radio  newspaper     sales
TV         1.000000  0.054809   0.056648  0.782224
radio      0.054809  1.000000   0.354104  0.576223
newspaper  0.056648  0.354104   1.000000  0.228299
sales      0.782224  0.576223   0.228299  1.000000

In [16]:
x=df.iloc[:,0:-1]

In [17]:
y=df.iloc[:,-1].values.reshape(-1,1)

In [18]:
lr=LinearRegression()

In [19]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y)

In [20]:
lr.fit(xtrain,ytrain)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [21]:
lr.score(xtrain,ytrain)

0.8871176582708422

In [23]:
pred_lr=lr.predict(xtest)

In [28]:
r2_score(pred_lr,ytest)

0.9182936832716274

In [69]:
cvlr=cross_val_score(lr,x,y,cv=15,scoring='r2')

In [70]:
cvlr.mean()

0.8722434812544485

In [71]:
cvlr.std()

0.0790003809663784

In [72]:
cvlr

array([0.77365797, 0.89931899, 0.88894743, 0.93175573, 0.93367939,
       0.71429954, 0.92664171, 0.94439136, 0.9423114 , 0.71152538,
       0.92076147, 0.88511231, 0.79281889, 0.90037449, 0.91805614])

In [40]:
dtr=DecisionTreeRegressor()

In [41]:
dtr.fit(xtrain,ytrain)

DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
                      max_leaf_nodes=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      presort=False, random_state=None, splitter='best')

In [42]:
dtr.score(xtrain,ytrain)

1.0

In [43]:
pred_dtr=dtr.predict(xtest)

In [44]:
r2_score(pred_dtr,ytest)

0.9519623089971048

In [46]:
cvd=cross_val_score(dtr,x,y,cv=20,scoring='r2')

In [47]:
cvd

array([0.95702817, 0.97277365, 0.93527314, 0.96900161, 0.95790994,
       0.96594788, 0.92929872, 0.88617   , 0.81773318, 0.94320981,
       0.95490299, 0.86905202, 0.9827149 , 0.92059952, 0.94869038,
       0.91736882, 0.89232553, 0.97294708, 0.99167654, 0.98069923])

In [48]:
cvd.mean()

0.9382661563230815

In [49]:
cvd.std()

0.04293175543479308

In [53]:
dtr.feature_importances_

array([0.60697638, 0.36581814, 0.02720548])

In [55]:
rfr=RandomForestRegressor()

In [56]:
rfr.fit(xtrain,ytrain)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
                      max_features='auto', max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, n_estimators=10,
                      n_jobs=None, oob_score=False, random_state=None,
                      verbose=0, warm_start=False)

In [57]:
rfr.score(xtrain,ytrain)

0.9934653275681395

In [58]:
pred_rfr=rfr.predict(xtest)

In [59]:
r2_score(pred_rfr,ytest)

0.9777619174741757

In [60]:
cvr=cross_val_score(rfr,x,y,cv=15,scoring='r2')

In [61]:
cvr.mean()

0.9658361348206549

In [62]:
cvr.std()

0.01596486810010553

In [63]:
ada=AdaBoostRegressor(base_estimator=rfr)

In [64]:
ada.fit(xtrain,ytrain)

AdaBoostRegressor(base_estimator=RandomForestRegressor(bootstrap=True,
                                                       criterion='mse',
                                                       max_depth=None,
                                                       max_features='auto',
                                                       max_leaf_nodes=None,
                                                       min_impurity_decrease=0.0,
                                                       min_impurity_split=None,
                                                       min_samples_leaf=1,
                                                       min_samples_split=2,
                                                       min_weight_fraction_leaf=0.0,
                                                       n_estimators=10,
                                                       n_jobs=None,
                                                       oob_score=False,
                        

In [65]:
ada.score(xtrain,ytrain)

0.9984302575534009

In [66]:
pred_ada=ada.predict(xtest)

In [67]:
r2_score(pred_ada,ytest)

0.9825929137854743

In [73]:
cva=cross_val_score(ada,x,y,cv=15,scoring='r2')

In [77]:
cva.mean()

98.01101194519643

In [76]:
cva.std()*100

0.9135043232083618

In [79]:
sales_model=pickle.dumps(cva)