In [61]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import warnings
warnings.filterwarnings('ignore')
from sklearn.neighbors import KNeighborsClassifier
from sklearn.decomposition import PCA
from sklearn.model_selection import GridSearchCV
import pickle
from sklearn.model_selection import cross_val_score
from sklearn.metrics import precision_score, recall_score
import pickle

In [2]:
df=pd.read_csv('sbi.csv')

In [3]:
df.head()

age  sex     bmi  children  smoker  region      charges  insuranceclaim
0   19    0  27.900         0       1       3  16884.92400               1
1   18    1  33.770         1       0       2   1725.55230               1
2   28    1  33.000         3       0       2   4449.46200               0
3   33    1  22.705         0       0       1  21984.47061               0
4   32    1  28.880         0       0       1   3866.85520               1

In [4]:
df.describe()

age          sex          bmi     children       smoker  \
count  1338.000000  1338.000000  1338.000000  1338.000000  1338.000000   
mean     39.207025     0.505232    30.663397     1.094918     0.204783   
std      14.049960     0.500160     6.098187     1.205493     0.403694   
min      18.000000     0.000000    15.960000     0.000000     0.000000   
25%      27.000000     0.000000    26.296250     0.000000     0.000000   
50%      39.000000     1.000000    30.400000     1.000000     0.000000   
75%      51.000000     1.000000    34.693750     2.000000     0.000000   
max      64.000000     1.000000    53.130000     5.000000     1.000000   

            region       charges  insuranceclaim  
count  1338.000000   1338.000000     1338.000000  
mean      1.515695  13270.422265        0.585202  
std       1.104885  12110.011237        0.492871  
min       0.000000   1121.873900        0.000000  
25%       1.000000   4740.287150        0.000000  
50%       2.000000   9382.033000        1.000000  
75%       2.000000  16639.912515        1.000000  
max       3.000000  63770.428010        1.000000

In [5]:
df.corr()

age       sex       bmi  children    smoker    region  \
age             1.000000 -0.020856  0.109272  0.042469 -0.025019  0.002127   
sex            -0.020856  1.000000  0.046371  0.017163  0.076185  0.004588   
bmi             0.109272  0.046371  1.000000  0.012759  0.003750  0.157566   
children        0.042469  0.017163  0.012759  1.000000  0.007673  0.016569   
smoker         -0.025019  0.076185  0.003750  0.007673  1.000000 -0.002181   
region          0.002127  0.004588  0.157566  0.016569 -0.002181  1.000000   
charges         0.299008  0.057292  0.198341  0.067998  0.787251 -0.006208   
insuranceclaim  0.113723  0.031565  0.384198 -0.409526  0.333261  0.020891   

                 charges  insuranceclaim  
age             0.299008        0.113723  
sex             0.057292        0.031565  
bmi             0.198341        0.384198  
children        0.067998       -0.409526  
smoker          0.787251        0.333261  
region         -0.006208        0.020891  
charges         1.000000        0.309418  
insuranceclaim  0.309418        1.000000

In [6]:
df.skew()

age               0.055673
sex              -0.020951
bmi               0.284047
children          0.938380
smoker            1.464766
region           -0.038101
charges           1.515880
insuranceclaim   -0.346254
dtype: float64

In [7]:
x=df.iloc[:,0:-1]

In [8]:
y=df.iloc[:,-1].values.reshape(-1,1)

In [9]:
list=np.arange(0,100)

In [12]:
for m in list:
    xtrain,xtest,ytrain,ytest=train_test_split(x,y,random_state=m)
    lr.fit(xtrain,ytrain)
    pred=lr.predict(xtest)
    ascore=accuracy_score(pred,ytest)
    if ascore>0.8:
        print(m,ascore)

6 0.8597014925373134
8 0.8059701492537313
9 0.8298507462686567
11 0.8208955223880597
12 0.8059701492537313
18 0.8059701492537313
22 0.8208955223880597
24 0.844776119402985
27 0.8208955223880597
28 0.8149253731343283
31 0.8029850746268656
32 0.8328358208955224
34 0.808955223880597
35 0.8119402985074626
44 0.8059701492537313
45 0.8208955223880597
47 0.8238805970149253
49 0.8029850746268656
50 0.8388059701492537
52 0.8298507462686567
54 0.808955223880597
56 0.8149253731343283
58 0.8059701492537313
62 0.8029850746268656
69 0.8238805970149253
71 0.8029850746268656
80 0.826865671641791
82 0.8059701492537313
90 0.8119402985074626
91 0.808955223880597
92 0.8238805970149253
94 0.8149253731343283
97 0.8149253731343283


In [13]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y)

In [14]:
lr=LogisticRegression()

In [15]:
lr.fit(xtrain,ytrain)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [16]:
lr.score(xtrain,ytrain)

0.7956131605184447

In [17]:
pred=lr.predict(xtest)

In [18]:
accuracy_score(pred,ytest)

0.7850746268656716

In [19]:
cv=cross_val_score(lr,x,y,cv=10,scoring='accuracy')

In [20]:
cv.mean()

0.7959585115358878

In [21]:
dtc=DecisionTreeClassifier()

In [22]:
dtc.fit(xtrain,ytrain)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [23]:
pred_dtc=dtc.predict(xtest)

In [24]:
accuracy_score(pred_dtc,ytest)

0.9880597014925373

In [25]:
cvd=cross_val_score(dtc,x,y,cv=10,scoring='accuracy')

In [26]:
cvd.mean()

0.97831290498219

In [27]:
confusion_matrix(pred_dtc,ytest)

array([[139,   1],
       [  3, 192]], dtype=int64)

In [28]:
cvd.std()

0.019637721131946097

In [29]:
dtc.feature_importances_

array([0.06452086, 0.        , 0.40166898, 0.33763947, 0.18709213,
       0.        , 0.00907856])

In [30]:
x.columns

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'charges'], dtype='object')

In [31]:
lr.coef_

array([[-2.70795166e-02, -1.01897463e-01,  7.12156676e-02,
        -1.19146640e+00,  1.70891834e-01, -1.57397141e-01,
         1.07538063e-04]])

In [32]:
crit={'criterion':['gini','entropy']}

In [39]:
grid=GridSearchCV(estimator=dtc,param_grid=crit,cv=15,scoring='accuracy')

In [40]:
grid.fit(x,y)
grid.best_score_

0.9895366218236173

In [41]:
grid.best_params_

{'criterion': 'entropy'}

In [49]:
dtcc=DecisionTreeClassifier(criterion='gini')

In [50]:
dtcc.fit(xtrain,ytrain)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [51]:
dtcc.score(xtrain,ytrain)

1.0

In [52]:
dtc.score(xtrain,ytrain)

1.0

In [53]:
pred_dtcc=dtcc.predict(xtest)

In [54]:
accuracy_score(pred_dtcc,ytest)

0.9880597014925373

In [56]:
precision_score(pred_dtc,ytest)


0.9948186528497409

In [57]:
recall_score(pred_dtc,ytest)

0.9846153846153847

In [59]:
print(classification_report(pred_dtc,ytest))

              precision    recall  f1-score   support

           0       0.98      0.99      0.99       140
           1       0.99      0.98      0.99       195

    accuracy                           0.99       335
   macro avg       0.99      0.99      0.99       335
weighted avg       0.99      0.99      0.99       335



In [60]:
confusion_matrix(pred_dtc,ytest)

array([[139,   1],
       [  3, 192]], dtype=int64)

In [63]:
sbi_dtc=pickle.dumps(dtc)