In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import warnings
warnings.filterwarnings('ignore')
from sklearn.neighbors import KNeighborsClassifier
from sklearn.decomposition import PCA
from sklearn.model_selection import GridSearchCV
import pickle
from sklearn.model_selection import cross_val_score

In [396]:
col=np.arange(0,61)

In [397]:
df=pd.read_csv('sonar.csv',names=col)

In [398]:
df.head()

0       1       2       3       4       5       6       7       8   \
0  0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109   
1  0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
2  0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
3  0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
4  0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   

       9   ...      51      52      53      54      55      56      57  \
0  0.2111  ...  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180  0.0084   
1  0.2872  ...  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140  0.0049   
2  0.6194  ...  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316  0.0164   
3  0.1264  ...  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050  0.0044   
4  0.4459  ...  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072  0.0048   

       58      59  60  
0  0.0090  0.0032   R  
1  0.0052  0.0044   R  
2  0.0095  0.0078   R  
3  0.0040  0.0117   R  
4  0.0107  0.0094   R  

[5 rows x 61 columns]

In [399]:
df.describe()

0           1           2           3           4           5   \
count  208.000000  208.000000  208.000000  208.000000  208.000000  208.000000   
mean     0.029164    0.038437    0.043832    0.053892    0.075202    0.104570   
std      0.022991    0.032960    0.038428    0.046528    0.055552    0.059105   
min      0.001500    0.000600    0.001500    0.005800    0.006700    0.010200   
25%      0.013350    0.016450    0.018950    0.024375    0.038050    0.067025   
50%      0.022800    0.030800    0.034300    0.044050    0.062500    0.092150   
75%      0.035550    0.047950    0.057950    0.064500    0.100275    0.134125   
max      0.137100    0.233900    0.305900    0.426400    0.401000    0.382300   

               6           7           8           9   ...          50  \
count  208.000000  208.000000  208.000000  208.000000  ...  208.000000   
mean     0.121747    0.134799    0.178003    0.208259  ...    0.016069   
std      0.061788    0.085152    0.118387    0.134416  ...    0.012008   
min      0.003300    0.005500    0.007500    0.011300  ...    0.000000   
25%      0.080900    0.080425    0.097025    0.111275  ...    0.008425   
50%      0.106950    0.112100    0.152250    0.182400  ...    0.013900   
75%      0.154000    0.169600    0.233425    0.268700  ...    0.020825   
max      0.372900    0.459000    0.682800    0.710600  ...    0.100400   

               51          52          53          54          55          56  \
count  208.000000  208.000000  208.000000  208.000000  208.000000  208.000000   
mean     0.013420    0.010709    0.010941    0.009290    0.008222    0.007820   
std      0.009634    0.007060    0.007301    0.007088    0.005736    0.005785   
min      0.000800    0.000500    0.001000    0.000600    0.000400    0.000300   
25%      0.007275    0.005075    0.005375    0.004150    0.004400    0.003700   
50%      0.011400    0.009550    0.009300    0.007500    0.006850    0.005950   
75%      0.016725    0.014900    0.014500    0.012100    0.010575    0.010425   
max      0.070900    0.039000    0.035200    0.044700    0.039400    0.035500   

               57          58          59  
count  208.000000  208.000000  208.000000  
mean     0.007949    0.007941    0.006507  
std      0.006470    0.006181    0.005031  
min      0.000300    0.000100    0.000600  
25%      0.003600    0.003675    0.003100  
50%      0.005800    0.006400    0.005300  
75%      0.010350    0.010325    0.008525  
max      0.044000    0.036400    0.043900  

[8 rows x 60 columns]

In [400]:
df.shape

(208, 61)

In [401]:
from sklearn.preprocessing import LabelEncoder

In [402]:
le=LabelEncoder()

In [403]:
y=df.iloc[:,-1].values.reshape(-1,1)

In [404]:
x=df.iloc[:,0:-1]

In [405]:
x.shape

(208, 60)

In [406]:
y=le.fit_transform(y)

In [407]:
y=y.reshape(-1,1)

In [408]:
list=np.arange(0,100)

In [409]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y)

In [410]:
lr=LogisticRegression()

In [411]:
lr.fit(xtrain,ytrain)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [412]:
lr.score(xtrain,ytrain)

0.8141025641025641

In [413]:
lr_pred=lr.predict(xtest)

In [414]:
accuracy_score(lr_pred,ytest)

0.7692307692307693

In [415]:
confusion_matrix(lr_pred,ytest)

array([[21,  7],
       [ 5, 19]], dtype=int64)

In [416]:
print(classification_report(lr_pred,ytest))

              precision    recall  f1-score   support

           0       0.81      0.75      0.78        28
           1       0.73      0.79      0.76        24

    accuracy                           0.77        52
   macro avg       0.77      0.77      0.77        52
weighted avg       0.77      0.77      0.77        52



In [417]:
cv=cross_val_score(lr,x,y,cv=20,scoring='accuracy')

In [418]:
cv.mean()

0.7123232323232324

In [450]:
models=[GaussianNB(),DecisionTreeClassifier('entropy'),RandomForestClassifier(),SVC(kernel='rbf')]

In [516]:
for m in models:
    m.fit(xtrain,ytrain)
    predm=m.predict(xtest)
    print('accuracy score of', m, 'is:')
    print(accuracy_score(predm,ytest))
    print(confusion_matrix(predm,ytest))
    print(classification_report(predm,ytest))

accuracy score of GaussianNB(priors=None, var_smoothing=1e-09) is:
0.6923076923076923
[[14  4]
 [12 22]]
              precision    recall  f1-score   support

           0       0.54      0.78      0.64        18
           1       0.85      0.65      0.73        34

    accuracy                           0.69        52
   macro avg       0.69      0.71      0.68        52
weighted avg       0.74      0.69      0.70        52

accuracy score of DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best') is:
0.7692307692307693
[[20  6]
 [ 6 20]]
              precision    recall  f1-score   support

           0       0.77      0.77      0.77  

In [507]:
rfr=RandomForestClassifier()

In [453]:
cvr=cross_val_score(rfr,x,y,cv=15,scoring='accuracy')

In [454]:
cvr.mean()

0.7122344322344322

In [455]:
adalr=AdaBoostClassifier(n_estimators=200,base_estimator=lr)

In [456]:
adalr.fit(xtrain,ytrain)

AdaBoostClassifier(algorithm='SAMME.R',
                   base_estimator=LogisticRegression(C=1.0, class_weight=None,
                                                     dual=False,
                                                     fit_intercept=True,
                                                     intercept_scaling=1,
                                                     l1_ratio=None,
                                                     max_iter=100,
                                                     multi_class='warn',
                                                     n_jobs=None, penalty='l2',
                                                     random_state=None,
                                                     solver='warn', tol=0.0001,
                                                     verbose=0,
                                                     warm_start=False),
                   learning_rate=1.0, n_estimators=200, random_state=None)

In [457]:
adalr.score(xtrain,ytrain)

0.8397435897435898

In [458]:
adapred=adalr.predict(xtest)

In [459]:
accuracy_score(adapred,ytest)

0.7884615384615384

In [460]:
cv=cross_val_score(adalr,x,y,cv=15,scoring='accuracy').mean()

In [461]:
cvs=cross_val_score(adalr,x,y,cv=15,scoring='accuracy').std()

In [462]:
cv

0.6856166056166055

In [463]:
cvs

0.19689492404917164

In [464]:
gb=GaussianNB()

In [465]:
dtc=DecisionTreeClassifier()

In [466]:
adagb=AdaBoostClassifier(n_estimators=200,base_estimator=gb)

In [467]:
adagb.fit(xtrain,ytrain)
adagb.score(xtrain,ytrain)
adapredgb=adagb.predict(xtest)
accuracy_score(adapredgb,ytest)

0.6538461538461539

In [468]:
cvg=cross_val_score(adagb,x,y,cv=15,scoring='accuracy').mean()
cvsg=cross_val_score(adagb,x,y,cv=15,scoring='accuracy').std()

In [469]:
cvg


0.674041514041514

In [470]:
cvsg

0.12757170342817076

In [471]:
adad=AdaBoostClassifier(n_estimators=200,base_estimator=dtc)

In [472]:
adad.fit(xtrain,ytrain)
adad.score(xtrain,ytrain)
adapredd=adad.predict(xtest)
accuracy_score(adapredd,ytest)

0.7692307692307693

In [473]:
cvd=cross_val_score(adad,x,y,cv=15,scoring='accuracy').mean()
cvsd=cross_val_score(adad,x,y,cv=15,scoring='accuracy').std()

In [474]:
cvd

0.5854945054945055

In [475]:
cvsd

0.1602843345634642

In [517]:
adar=AdaBoostClassifier(n_estimators=200,base_estimator=rfr)

In [518]:
adar.fit(xtrain,ytrain)
adar.score(xtrain,ytrain)
adapredr=adar.predict(xtest)
accuracy_score(adapredr,ytest)

0.8653846153846154

In [519]:
cvr=cross_val_score(adar,x,y,cv=15,scoring='accuracy').mean()
cvsr=cross_val_score(adar,x,y,cv=15,scoring='accuracy').std()

In [520]:
cvr

0.7409523809523808

In [521]:
cvsr

0.1535532417115852

In [271]:
imp=np.array(adar.feature_importances_)

In [272]:
cols=x.columns

In [273]:
imp_f=pd.DataFrame({'importance':imp, 'feature name':cols} )

In [274]:
print(imp_f.sort_values('importance',ascending=False))

    importance  feature name
53    0.035618            53
52    0.029050            52
54    0.026353            54
58    0.023790            58
45    0.023132            45
56    0.023060            56
36    0.023040            36
30    0.022284            30
21    0.021751            21
38    0.021647            38
39    0.021610            39
20    0.021527            20
44    0.021400            44
5     0.021295             5
1     0.019917             1
28    0.019681            28
48    0.019440            48
24    0.019289            24
7     0.019197             7
33    0.018685            33
11    0.018268            11
55    0.018253            55
41    0.017725            41
35    0.017359            35
49    0.017276            49
4     0.016968             4
22    0.016482            22
25    0.016472            25
23    0.016254            23
0     0.016134             0
9     0.015642             9
32    0.015627            32
6     0.015094             6
59    0.015066

In [522]:
sonar_model=pickle.dumps(adar)